# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {filemgmt 20-1318}  -suppress 
set_msg_config  -id {Synth 8-350}  -string {{WARNING: [Synth 8-350] instance 'Max_H' of module 'comparator' requires 5 connections, but only 3 given [/afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/vga.sv:31]}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/vivadoTest/vivadoTest.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/vivadoTest/vivadoTest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/playfieldRAM.sv
  /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/pixelLookup.sv
  /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/motionObjects.sv
  /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/computeTile.sv
  /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/vga.sv
  /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/graphicsPipeline.sv
}
read_xdc /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/vivadoTest/vivadoTest.srcs/constrs_1/imports/18-545/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/cnordgre/Private/18545/545_Project/centipede/graphics/vivadoTest/vivadoTest.srcs/constrs_1/imports/18-545/Nexys4_Master.xdc]

synth_design -top graphicsPipeline -part xc7a100tcsg324-1
write_checkpoint -noxdef graphicsPipeline.dcp
catch { report_utilization -file graphicsPipeline_utilization_synth.rpt -pb graphicsPipeline_utilization_synth.pb }
