# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/rsaigal/18-545/Pokey_tb/Pokey_tb.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/rsaigal/18-545/Pokey_tb/Pokey_tb.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /afs/ece.cmu.edu/usr/rsaigal/18-545/Pokey_tb/Pokey_tb.srcs/sources_1/imports/Audio/pokeyaudio.v
synth_design -top pokeyaudio -part xc7vx485tffg1157-1
write_checkpoint -noxdef pokeyaudio.dcp
catch { report_utilization -file pokeyaudio_utilization_synth.rpt -pb pokeyaudio_utilization_synth.pb }
